version: '3.8'

services:
  jobtalk_app:
    image: ${CI_REGISTRY_IMAGE}:${IMAGE_TAG:-latest}
    container_name: jobtalk_admin_prod
    restart: unless-stopped
    environment:
      # MongoDB Atlas
      MONGO_URL: ${MONGO_URL}
      DB_NAME: ${DB_NAME:-recruitment_admin_prod}
      
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM:-HS256}
      JWT_EXPIRY_HOURS: ${JWT_EXPIRY_HOURS:-8}
      
      # Encryption
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      
      # AWS SES
      APP_NAME: ${APP_NAME:-JobTalk}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      
      # Application
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-8001}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
    ports:
      - "80:80"
      - "8001:8001"
    volumes:
      - app_logs:/app/logs
    networks:
      - jobtalk_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  app_logs:
    driver: local

networks:
  jobtalk_network:
    driver: bridge
